### ISSUE TITLE
Kubernetes warns about hostPath volume type.

### ISSUE THREAD

**Issue by ChristianAmmer** [lacework/lacework-agent-releases#13]
The deployment files for installing the [lacework agent on Kubernetes](https://docs.lacework.net/onboarding/deploy-on-kubernetes#deploy-with-a-daemonset) contain `hostPath` volume mounts. From the `lacework-k8s.yaml` file:

```yaml
        volumeMounts:
          - name: sys
            mountPath: /sys
      volumes:
        - name: dev
          hostPath:
              path: /dev
        - name: sys
          hostPath:
              path: /sys
```

This leads to the problem that container tools deployed in the Lacework container do not work properly because, for example, they assume that the cgroup root is at /sys/fs/cgroup/. For example, the container's memory limit should be available via /sys/fs/cgroup/memory/memory.limit_in_bytes (e.g. as documented for Docker in Setting Hard Memory Limits). But with the sys mount, the container has the container node view instead.

Additionally, the Kubernetes documentation recommends not using hostPath volume types as they pose a security risk:

This leads to the problem that container tools deployed into the `lacework` container will not work properly because they expect that the cgroup root is at `/sys/fs/cgroup/`. For example, the container's memory limit should be available via `/sys/fs/cgroup/memory/memory.limit_in_bytes` (e.g. as documented for Docker in [Specify hard limits on memory](https://docs.docker.com/reference/cli/docker/container/run/#memory). But with the `sys` mount, the container has the node view instead.

Additionally, the [Kubernetes documentation recommends not using `hostPath` volume types as they introduce a security risk](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath):
> Warning:
Using the hostPath volume type presents many security risks. If you can avoid using a hostPath volume, you should. For example, define a [local PersistentVolume](https://kubernetes.io/docs/concepts/storage/volumes/#local), and use that instead.
